### ISSUE TITLE
inspec plugin install train-aws", it is taking me forever to complete installation

### ISSUE THREAD

**Issue by aminep7** [inspec/train-aws#25] opened 2019-07-12 19:22 UTC
**Describe the bug**
When i run "inspec plugin install train-aws", it is taking me forever , looks like it will never complete.

**To Reproduce**
1. Just run inspec plugin install train-aws

**Expected behavior**
After running inspec plugin install train-aws, it should display some kind of installation complete message.

**Screenshots**
![image](https://user-images.githubusercontent.com/36433215/61153130-e9c8e500-a4af-11e9-9029-c81f8ac143b3.png)

**Version Information:**
 - InSpec/Chef version:  inspec version 4.7.3

 - aws-sdk version: , aws-sdk-core: v3.59.0

 - train-aws plugin version:train-aws: v0.1.7

**Additional context**

**Comment by clintoncwolfe** [comment] 2019-07-23 16:19
This is actually caused by https://github.com/inspec/inspec/issues/3799 , which is fixed in inspec 4.7.18 .

Thanks for reporting!

**Closed by clintoncwolfe** 2019-07-23 16:19 UTC
Labels: Triage/Declined, Type/Bug
